# Generated by Django 3.1 on 2020-08-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
