# Generated by Django 3.1 on 2020-08-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productgallery_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='price',
        ),
    ]
