# Generated by Django 3.1 on 2020-08-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='auction_url',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
