# Generated by Django 3.1 on 2020-09-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200825_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='mark',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
